// ─── Exportação de candidatura ─────────────────────────────────────────────────
// Gera um pacote completo: recruiter message, cover paragraph, checklist e metadados.
// Saída: texto puro copiável + blob para download como .txt

import type { TrackedJob } from "@/lib/radar-types";
import type { CandidateProfile } from "@/lib/profile";
import { buildCustomCoverParagraph, buildRecruiterMessage, analyzeJobMatch, parseJobDescription } from "@/lib/job-intake";

export type CandidacyPackage = {
  jobTitle: string;
  company: string;
  score: number;
  status: string;
  sourceUrl?: string;
  recruiterMessage: string;
  coverParagraph: string;
  checklist: string[];
  exportedAt: string;
  plainText: string;
};

const APPLY_CHECKLIST = [
  "Review JD one more time before applying",
  "Customise CV headline to match job title",
  "Add cover paragraph to application form",
  "Copy recruiter message and send via LinkedIn/email",
  "Set follow-up reminder for 7 days",
  "Log application date in Argus (set status → Applied)",
];

export function buildCandidacyPackage(
  job: TrackedJob,
  profile: CandidateProfile,
  lang: "en" | "de" | "pt" = "en",
): CandidacyPackage {
  // Recalcular match para ter analysis fresca
  const parsed   = parseJobDescription(job.summary ?? "");
  const analysis = analyzeJobMatch(parsed, profile);

  const recruiterMessage = job.recruiterMessage ??
    buildRecruiterMessage(parsed, profile, analysis, lang);

  const coverParagraph = buildCustomCoverParagraph(parsed, profile, analysis, lang);

  const checklist = [...APPLY_CHECKLIST];
  if (job.languages?.includes("German")) {
    checklist.splice(2, 0, "Confirm German language level matches requirement");
  }
  if (job.sourceUrl) {
    checklist.push(`Apply at: ${job.sourceUrl}`);
  }

  const exportedAt = new Date().toLocaleString("en-GB", { timeZone: "Europe/Berlin" });

  const separator = "─".repeat(60);

  const plainText = [
    `ARGUS — APPLICATION PACKAGE`,
    `Exported: ${exportedAt}`,
    separator,
    `Role:    ${job.title}`,
    `Company: ${job.company}`,
    `Score:   ${job.score}%  |  ${job.verdict}`,
    `Status:  ${job.status}`,
    job.sourceUrl ? `URL:     ${job.sourceUrl}` : "",
    separator,
    `RECRUITER MESSAGE`,
    separator,
    recruiterMessage,
    separator,
    `COVER PARAGRAPH`,
    separator,
    coverParagraph,
    separator,
    `APPLICATION CHECKLIST`,
    separator,
    ...checklist.map((item, i) => `  ${i + 1}. ${item}`),
    separator,
    `Generated by Argus — private job radar`,
  ].filter((l) => l !== "").join("\n");

  return {
    jobTitle: job.title,
    company: job.company,
    score: job.score,
    status: job.status,
    sourceUrl: job.sourceUrl,
    recruiterMessage,
    coverParagraph,
    checklist,
    exportedAt,
    plainText,
  };
}

export function downloadCandidacyPackage(pkg: CandidacyPackage): void {
  const blob     = new Blob([pkg.plainText], { type: "text/plain;charset=utf-8" });
  const url      = URL.createObjectURL(blob);
  const filename = `argus-${pkg.company.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${new Date().toISOString().slice(0, 10)}.txt`;
  const anchor   = document.createElement("a");
  anchor.href    = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}
